In [1]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1
    
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


In [2]:
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


In [3]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
print(OR(0, 0))
print(OR(1, 0))
print(OR(0, 1))
print(OR(1, 1))

0
1
1
1


In [4]:
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
print(NAND(0, 0))
print(NAND(1, 0))
print(NAND(0, 1))
print(NAND(1, 1))

1
1
1
0


In [5]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

print(XOR(0, 0))
print(XOR(1, 0))
print(XOR(0, 1))
print(XOR(1, 1))

0
1
1
0


In [7]:
import torch

In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6348, 0.4783, 0.9469],
        [0.9764, 0.5334, 0.5411],
        [0.2820, 0.9890, 0.7439],
        [0.6958, 0.9959, 0.2574],
        [0.9562, 0.1918, 0.6909]])


In [10]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = torch.tensor([2.5, 3.5])
print(x)

tensor([2.5000, 3.5000])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2569, -0.0282,  0.2802],
        [-0.3292, -0.3385, -1.2244],
        [ 0.2577,  0.0167, -1.3519],
        [ 0.5170,  0.7353,  0.1037],
        [-0.4790,  0.6879, -1.3278]])


In [13]:
print(x.size())
print(y.size())
a, b = x.size()
print(a, b)

torch.Size([5, 3])
torch.Size([5, 3])
5 3


In [15]:
rank_0_tensor = torch.tensor(4)
print(rank_0_tensor)

rank_1_tensor = torch.tensor([2.0, 3.0, 4.0])
print(rank_1_tensor)

rank_2_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float16)
print(rank_2_tensor)

tensor(4)
tensor([2., 3., 4.])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16)


In [16]:
rank_3_tensor = torch.tensor([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


In [17]:
print(x + y)
print(torch.add(x, y))

tensor([[ 2.2569,  0.9718,  1.2802],
        [ 0.6708,  0.6615, -0.2244],
        [ 1.2577,  1.0167, -0.3519],
        [ 1.5170,  1.7353,  1.1037],
        [ 0.5210,  1.6879, -0.3278]], dtype=torch.float64)
tensor([[ 2.2569,  0.9718,  1.2802],
        [ 0.6708,  0.6615, -0.2244],
        [ 1.2577,  1.0167, -0.3519],
        [ 1.5170,  1.7353,  1.1037],
        [ 0.5210,  1.6879, -0.3278]], dtype=torch.float64)


In [18]:
result = torch.zeros(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 2.2569,  0.9718,  1.2802],
        [ 0.6708,  0.6615, -0.2244],
        [ 1.2577,  1.0167, -0.3519],
        [ 1.5170,  1.7353,  1.1037],
        [ 0.5210,  1.6879, -0.3278]])


In [19]:
print(y)
y.add_(x)
print(y)

tensor([[ 1.2569, -0.0282,  0.2802],
        [-0.3292, -0.3385, -1.2244],
        [ 0.2577,  0.0167, -1.3519],
        [ 0.5170,  0.7353,  0.1037],
        [-0.4790,  0.6879, -1.3278]])
tensor([[ 2.2569,  0.9718,  1.2802],
        [ 0.6708,  0.6615, -0.2244],
        [ 1.2577,  1.0167, -0.3519],
        [ 1.5170,  1.7353,  1.1037],
        [ 0.5210,  1.6879, -0.3278]])


In [20]:
print(y[:, 1])

tensor([0.9718, 0.6615, 1.0167, 1.7353, 1.6879])


In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [25]:
f = x.flatten()
print(f.size())

x = torch.randn(4, 4, 3)
f = x.flatten(1)
print(f.size())


torch.Size([16])
torch.Size([4, 12])


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

In [ ]:
a.add_(1)
print(a)
print(b)

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
print(20*'-')
np.add(a, 1, out=a)
print(a)
print(b)