In [21]:
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1
    
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


In [22]:
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


In [23]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
print(OR(0, 0))
print(OR(1, 0))
print(OR(0, 1))
print(OR(1, 1))

0
1
1
1


In [24]:
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    
print(NAND(0, 0))
print(NAND(1, 0))
print(NAND(0, 1))
print(NAND(1, 1))

1
1
1
0


In [25]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

print(XOR(0, 0))
print(XOR(1, 0))
print(XOR(0, 1))
print(XOR(1, 1))

0
1
1
0


In [26]:
import torch

In [27]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.5525, -1.0750,  1.5437],
        [-0.3558,  0.2688, -0.5244],
        [-0.1605,  0.5240, -0.9731],
        [-0.1149, -1.6686,  0.2604],
        [-0.3460,  0.1163,  0.0321]])


In [28]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0690, 0.5368, 0.2172],
        [0.6602, 0.4275, 0.0125],
        [0.1684, 0.7674, 0.9430],
        [0.7413, 0.5080, 0.1711],
        [0.6900, 0.4394, 0.3123]])


In [29]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [30]:
x = torch.tensor([2.5, 3.5])
print(x)

tensor([2.5000, 3.5000])


In [31]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1913,  0.1702,  0.5442],
        [ 0.3467, -0.7905, -1.1380],
        [ 0.0437, -1.9117,  1.6265],
        [-1.7044, -0.9828, -0.1467],
        [ 1.4953, -2.0119, -2.5557]])


In [32]:
print(x.size())
print(y.size())
a, b = x.size()
print(a, b)

torch.Size([5, 3])
torch.Size([5, 3])
5 3


In [33]:
rank_0_tensor = torch.tensor(4)
print(rank_0_tensor)

rank_1_tensor = torch.tensor([2.0, 3.0, 4.0])
print(rank_1_tensor)

rank_2_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float16)
print(rank_2_tensor)

tensor(4)
tensor([2., 3., 4.])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16)


In [34]:
rank_3_tensor = torch.tensor([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])
print(rank_3_tensor)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])


In [35]:
print(x + y)
print(torch.add(x, y))

tensor([[ 2.1913,  1.1702,  1.5442],
        [ 1.3467,  0.2095, -0.1380],
        [ 1.0437, -0.9117,  2.6265],
        [-0.7044,  0.0172,  0.8533],
        [ 2.4953, -1.0119, -1.5557]], dtype=torch.float64)
tensor([[ 2.1913,  1.1702,  1.5442],
        [ 1.3467,  0.2095, -0.1380],
        [ 1.0437, -0.9117,  2.6265],
        [-0.7044,  0.0172,  0.8533],
        [ 2.4953, -1.0119, -1.5557]], dtype=torch.float64)


In [39]:
result = torch.zeros(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 2.1913,  1.1702,  1.5442],
        [ 1.3467,  0.2095, -0.1380],
        [ 1.0437, -0.9117,  2.6265],
        [-0.7044,  0.0172,  0.8533],
        [ 2.4953, -1.0119, -1.5557]])


In [40]:
print(y)
y.add_(x)
print(y)

tensor([[ 1.1913,  0.1702,  0.5442],
        [ 0.3467, -0.7905, -1.1380],
        [ 0.0437, -1.9117,  1.6265],
        [-1.7044, -0.9828, -0.1467],
        [ 1.4953, -2.0119, -2.5557]])
tensor([[ 2.1913,  1.1702,  1.5442],
        [ 1.3467,  0.2095, -0.1380],
        [ 1.0437, -0.9117,  2.6265],
        [-0.7044,  0.0172,  0.8533],
        [ 2.4953, -1.0119, -1.5557]])


In [41]:
print(y[:, 1])

tensor([ 1.1702,  0.2095, -0.9117,  0.0172, -1.0119])


In [42]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [43]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8816])
0.8815661668777466


In [44]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [45]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [46]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [47]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
print(20*'-')
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
--------------------
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
