In [1]:
import torch
from torch import nn

rnn = nn.RNN(5, 6, 1)
input = torch.randn(4, 1, 5)
h0 = torch.zeros(1, 1, 6)
output, hn = rnn(input, h0)
print(input)
print(output)
print(hn)

tensor([[[ 0.6239, -1.1810, -0.3002, -1.5603,  0.0907]],

        [[ 1.5535,  0.8690,  0.2811, -0.0804,  0.4148]],

        [[ 0.1580,  0.8594,  0.5457, -1.1841,  0.5880]],

        [[ 1.2040,  0.0691,  0.9511, -0.5362, -1.1651]]])
tensor([[[-0.5627,  0.7014, -0.3620, -0.2961, -0.0437,  0.2179]],

        [[ 0.6763, -0.3637, -0.5154, -0.0915, -0.0013,  0.3857]],

        [[-0.1020,  0.4541,  0.0745, -0.2153, -0.5341, -0.4034]],

        [[ 0.6084, -0.1061,  0.4672,  0.1353,  0.1425,  0.4619]]],
       grad_fn=<StackBackward0>)
tensor([[[ 0.6084, -0.1061,  0.4672,  0.1353,  0.1425,  0.4619]]],
       grad_fn=<StackBackward0>)


In [2]:
lstm = nn.LSTM(5, 6, 1)
input = torch.randn(4, 1, 5)
h0 = torch.zeros(1, 1, 6)
c0 = torch.zeros(1, 1, 6)

output, (hn, cn) = lstm(input, (h0, c0))
print(input)
print(output)
print(hn)
print(cn)

tensor([[[ 0.1214,  1.4013, -0.8282, -0.6490, -0.6444]],

        [[-1.3884, -0.4219,  0.9662,  0.8994,  0.9114]],

        [[ 0.7463,  1.0022,  0.1587, -0.9399,  0.2633]],

        [[ 0.5525,  0.0758, -0.0900,  0.2946,  0.7047]]])
tensor([[[-0.0949, -0.1497, -0.0559, -0.0066, -0.1607, -0.0087]],

        [[-0.0065, -0.0682, -0.0578,  0.1449, -0.0812, -0.2522]],

        [[ 0.1471, -0.1003, -0.0151,  0.0756, -0.2017, -0.1428]],

        [[ 0.1753, -0.0899, -0.0483,  0.1571, -0.2274, -0.2221]]],
       grad_fn=<MkldnnRnnLayerBackward0>)
tensor([[[ 0.1753, -0.0899, -0.0483,  0.1571, -0.2274, -0.2221]]],
       grad_fn=<StackBackward0>)
tensor([[[ 0.3133, -0.2235, -0.0920,  0.2632, -0.4249, -0.3891]]],
       grad_fn=<StackBackward0>)


In [3]:
gru = nn.GRU(5, 6, 1)
input = torch.randn(4, 1, 5)
h0 = torch.zeros(1, 1, 6)
output, hn = gru(input, h0)

print(input)
print(output)
print(hn)

tensor([[[-1.5407,  1.1341,  2.2486,  1.5365, -1.5767]],

        [[-0.6710,  0.5718, -0.7531, -1.2667, -0.1710]],

        [[ 0.7044, -1.5787,  0.6929,  1.6572,  1.3430]],

        [[-2.3536,  0.7415, -0.3685,  0.4557, -0.0927]]])
tensor([[[-4.0060e-01, -6.0356e-03, -2.5922e-01, -1.4083e-01, -9.9261e-02,
           2.9266e-01]],

        [[-5.3890e-01, -5.5163e-02, -1.9178e-01,  1.2123e-01,  2.4544e-01,
          -1.1389e-01]],

        [[ 1.8520e-01, -2.3449e-01, -2.1163e-02, -1.0576e-01, -1.8766e-01,
          -3.4464e-01]],

        [[-2.5257e-01, -3.6851e-01,  1.4174e-01,  1.5238e-01,  3.4581e-01,
           1.8048e-04]]], grad_fn=<StackBackward0>)
tensor([[[-2.5257e-01, -3.6851e-01,  1.4174e-01,  1.5238e-01,  3.4581e-01,
           1.8048e-04]]], grad_fn=<StackBackward0>)
